# Make file for pgd_testbench

all: appointments

appointments: appointments_testing.cpp
	g++ -g -std=c++20 appointments_testing.cpp -o appointments

filesys: manipulate_filesystem.cpp
	g++ -g -std=c++20 manipulate_filesystem.cpp -o filesys